/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace distribution_service
{

  public partial class Chunk : TBase
  {
    private int _idMetadata;
    private string _chunkHash;

    public int IdMetadata
    {
      get
      {
        return _idMetadata;
      }
      set
      {
        __isset.idMetadata = true;
        this._idMetadata = value;
      }
    }

    public string ChunkHash
    {
      get
      {
        return _chunkHash;
      }
      set
      {
        __isset.chunkHash = true;
        this._chunkHash = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool idMetadata;
      public bool chunkHash;
    }

    public Chunk()
    {
    }

    public Chunk DeepCopy()
    {
      var tmp0 = new Chunk();
      if(__isset.idMetadata)
      {
        tmp0.IdMetadata = this.IdMetadata;
      }
      tmp0.__isset.idMetadata = this.__isset.idMetadata;
      if((ChunkHash != null) && __isset.chunkHash)
      {
        tmp0.ChunkHash = this.ChunkHash;
      }
      tmp0.__isset.chunkHash = this.__isset.chunkHash;
      return tmp0;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                IdMetadata = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                ChunkHash = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp1 = new TStruct("Chunk");
        await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
        var tmp2 = new TField();
        if(__isset.idMetadata)
        {
          tmp2.Name = "idMetadata";
          tmp2.Type = TType.I32;
          tmp2.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteI32Async(IdMetadata, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((ChunkHash != null) && __isset.chunkHash)
        {
          tmp2.Name = "chunkHash";
          tmp2.Type = TType.String;
          tmp2.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteStringAsync(ChunkHash, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is Chunk other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.idMetadata == other.__isset.idMetadata) && ((!__isset.idMetadata) || (global::System.Object.Equals(IdMetadata, other.IdMetadata))))
        && ((__isset.chunkHash == other.__isset.chunkHash) && ((!__isset.chunkHash) || (global::System.Object.Equals(ChunkHash, other.ChunkHash))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.idMetadata)
        {
          hashcode = (hashcode * 397) + IdMetadata.GetHashCode();
        }
        if((ChunkHash != null) && __isset.chunkHash)
        {
          hashcode = (hashcode * 397) + ChunkHash.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp3 = new StringBuilder("Chunk(");
      int tmp4 = 0;
      if(__isset.idMetadata)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("IdMetadata: ");
        IdMetadata.ToString(tmp3);
      }
      if((ChunkHash != null) && __isset.chunkHash)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("ChunkHash: ");
        ChunkHash.ToString(tmp3);
      }
      tmp3.Append(')');
      return tmp3.ToString();
    }
  }

}
