/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace distribution_service
{
  public partial class DistributionService
  {
    public interface IAsync
    {
      global::System.Threading.Tasks.Task MakeReplications(List<global::distribution_service.Chunk> @chunks, CancellationToken cancellationToken = default);

    }


    public class Client : TBaseClient, IDisposable, IAsync
    {
      public Client(TProtocol protocol) : this(protocol, protocol)
      {
      }

      public Client(TProtocol inputProtocol, TProtocol outputProtocol) : base(inputProtocol, outputProtocol)
      {
      }

      public async global::System.Threading.Tasks.Task MakeReplications(List<global::distribution_service.Chunk> @chunks, CancellationToken cancellationToken = default)
      {
        await send_MakeReplications(@chunks, cancellationToken);
        await recv_MakeReplications(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_MakeReplications(List<global::distribution_service.Chunk> @chunks, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("MakeReplications", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp5 = new InternalStructs.MakeReplications_args() {
          Chunks = @chunks,
        };
        
        await tmp5.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task recv_MakeReplications(CancellationToken cancellationToken = default)
      {
        
        var tmp6 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp6.Type == TMessageType.Exception)
        {
          var tmp7 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp7;
        }

        var tmp8 = new InternalStructs.MakeReplications_result();
        await tmp8.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
      }

    }

    public class AsyncProcessor : ITAsyncProcessor
    {
      private readonly IAsync _iAsync;
      private readonly ILogger<AsyncProcessor> _logger;

      public AsyncProcessor(IAsync iAsync, ILogger<AsyncProcessor> logger = default)
      {
        _iAsync = iAsync ?? throw new ArgumentNullException(nameof(iAsync));
        _logger = logger;
        processMap_["MakeReplications"] = MakeReplications_ProcessAsync;
      }

      protected delegate global::System.Threading.Tasks.Task ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken);
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot)
      {
        return await ProcessAsync(iprot, oprot, CancellationToken.None);
      }

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        try
        {
          var msg = await iprot.ReadMessageBeginAsync(cancellationToken);

          processMap_.TryGetValue(msg.Name, out var fn);

          if (fn == null)
          {
            await TProtocolUtil.SkipAsync(iprot, TType.Struct, cancellationToken);
            await iprot.ReadMessageEndAsync(cancellationToken);
            var x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            await oprot.WriteMessageBeginAsync(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID), cancellationToken);
            await x.WriteAsync(oprot, cancellationToken);
            await oprot.WriteMessageEndAsync(cancellationToken);
            await oprot.Transport.FlushAsync(cancellationToken);
            return true;
          }

          await fn(msg.SeqID, iprot, oprot, cancellationToken);

        }
        catch (IOException)
        {
          return false;
        }

        return true;
      }

      public async global::System.Threading.Tasks.Task MakeReplications_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp9 = new InternalStructs.MakeReplications_args();
        await tmp9.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp10 = new InternalStructs.MakeReplications_result();
        try
        {
          await _iAsync.MakeReplications(tmp9.Chunks, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("MakeReplications", TMessageType.Reply, seqid), cancellationToken); 
          await tmp10.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp11)
        {
          var tmp12 = $"Error occurred in {GetType().FullName}: {tmp11.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp11, tmp12);
          else
            Console.Error.WriteLine(tmp12);
          var tmp13 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("MakeReplications", TMessageType.Exception, seqid), cancellationToken);
          await tmp13.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

    }

    public class InternalStructs
    {

      public partial class MakeReplications_args : TBase
      {
        private List<global::distribution_service.Chunk> _chunks;

        public List<global::distribution_service.Chunk> Chunks
        {
          get
          {
            return _chunks;
          }
          set
          {
            __isset.@chunks = true;
            this._chunks = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @chunks;
        }

        public MakeReplications_args()
        {
        }

        public MakeReplications_args DeepCopy()
        {
          var tmp14 = new MakeReplications_args();
          if((Chunks != null) && __isset.@chunks)
          {
            tmp14.Chunks = this.Chunks.DeepCopy();
          }
          tmp14.__isset.@chunks = this.__isset.@chunks;
          return tmp14;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.List)
                  {
                    {
                      var _list15 = await iprot.ReadListBeginAsync(cancellationToken);
                      Chunks = new List<global::distribution_service.Chunk>(_list15.Count);
                      for(int _i16 = 0; _i16 < _list15.Count; ++_i16)
                      {
                        global::distribution_service.Chunk _elem17;
                        _elem17 = new global::distribution_service.Chunk();
                        await _elem17.ReadAsync(iprot, cancellationToken);
                        Chunks.Add(_elem17);
                      }
                      await iprot.ReadListEndAsync(cancellationToken);
                    }
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp18 = new TStruct("MakeReplications_args");
            await oprot.WriteStructBeginAsync(tmp18, cancellationToken);
            var tmp19 = new TField();
            if((Chunks != null) && __isset.@chunks)
            {
              tmp19.Name = "chunks";
              tmp19.Type = TType.List;
              tmp19.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
              await oprot.WriteListBeginAsync(new TList(TType.Struct, Chunks.Count), cancellationToken);
              foreach (global::distribution_service.Chunk _iter20 in Chunks)
              {
                await _iter20.WriteAsync(oprot, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is MakeReplications_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@chunks == other.__isset.@chunks) && ((!__isset.@chunks) || (global::System.Object.Equals(Chunks, other.Chunks))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Chunks != null) && __isset.@chunks)
            {
              hashcode = (hashcode * 397) + Chunks.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp21 = new StringBuilder("MakeReplications_args(");
          int tmp22 = 0;
          if((Chunks != null) && __isset.@chunks)
          {
            if(0 < tmp22++) { tmp21.Append(", "); }
            tmp21.Append("Chunks: ");
            Chunks.ToString(tmp21);
          }
          tmp21.Append(')');
          return tmp21.ToString();
        }
      }


      public partial class MakeReplications_result : TBase
      {

        public MakeReplications_result()
        {
        }

        public MakeReplications_result DeepCopy()
        {
          var tmp23 = new MakeReplications_result();
          return tmp23;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp24 = new TStruct("MakeReplications_result");
            await oprot.WriteStructBeginAsync(tmp24, cancellationToken);
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is MakeReplications_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return true;
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp25 = new StringBuilder("MakeReplications_result(");
          tmp25.Append(')');
          return tmp25.ToString();
        }
      }

    }

  }
}
