/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace server_service
{
  public partial class ServerService
  {
    public interface IAsync
    {
      global::System.Threading.Tasks.Task<global::server_service.Server> GetServer(int idServer, CancellationToken cancellationToken = default);

      global::System.Threading.Tasks.Task<List<global::server_service.VirtualNode>> GetVirtualNodes(CancellationToken cancellationToken = default);

    }


    public class Client : TBaseClient, IDisposable, IAsync
    {
      public Client(TProtocol protocol) : this(protocol, protocol)
      {
      }

      public Client(TProtocol inputProtocol, TProtocol outputProtocol) : base(inputProtocol, outputProtocol)
      {
      }

      public async global::System.Threading.Tasks.Task<global::server_service.Server> GetServer(int idServer, CancellationToken cancellationToken = default)
      {
        await send_GetServer(idServer, cancellationToken);
        return await recv_GetServer(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_GetServer(int idServer, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("GetServer", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp10 = new InternalStructs.GetServer_args() {
          IdServer = idServer,
        };
        
        await tmp10.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<global::server_service.Server> recv_GetServer(CancellationToken cancellationToken = default)
      {
        
        var tmp11 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp11.Type == TMessageType.Exception)
        {
          var tmp12 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp12;
        }

        var tmp13 = new InternalStructs.GetServer_result();
        await tmp13.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp13.__isset.success)
        {
          return tmp13.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "GetServer failed: unknown result");
      }

      public async global::System.Threading.Tasks.Task<List<global::server_service.VirtualNode>> GetVirtualNodes(CancellationToken cancellationToken = default)
      {
        await send_GetVirtualNodes(cancellationToken);
        return await recv_GetVirtualNodes(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_GetVirtualNodes(CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("GetVirtualNodes", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp14 = new InternalStructs.GetVirtualNodes_args() {
        };
        
        await tmp14.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<List<global::server_service.VirtualNode>> recv_GetVirtualNodes(CancellationToken cancellationToken = default)
      {
        
        var tmp15 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp15.Type == TMessageType.Exception)
        {
          var tmp16 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp16;
        }

        var tmp17 = new InternalStructs.GetVirtualNodes_result();
        await tmp17.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp17.__isset.success)
        {
          return tmp17.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "GetVirtualNodes failed: unknown result");
      }

    }

    public class AsyncProcessor : ITAsyncProcessor
    {
      private readonly IAsync _iAsync;
      private readonly ILogger<AsyncProcessor> _logger;

      public AsyncProcessor(IAsync iAsync, ILogger<AsyncProcessor> logger = default)
      {
        _iAsync = iAsync ?? throw new ArgumentNullException(nameof(iAsync));
        _logger = logger;
        processMap_["GetServer"] = GetServer_ProcessAsync;
        processMap_["GetVirtualNodes"] = GetVirtualNodes_ProcessAsync;
      }

      protected delegate global::System.Threading.Tasks.Task ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken);
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot)
      {
        return await ProcessAsync(iprot, oprot, CancellationToken.None);
      }

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        try
        {
          var msg = await iprot.ReadMessageBeginAsync(cancellationToken);

          processMap_.TryGetValue(msg.Name, out var fn);

          if (fn == null)
          {
            await TProtocolUtil.SkipAsync(iprot, TType.Struct, cancellationToken);
            await iprot.ReadMessageEndAsync(cancellationToken);
            var x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            await oprot.WriteMessageBeginAsync(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID), cancellationToken);
            await x.WriteAsync(oprot, cancellationToken);
            await oprot.WriteMessageEndAsync(cancellationToken);
            await oprot.Transport.FlushAsync(cancellationToken);
            return true;
          }

          await fn(msg.SeqID, iprot, oprot, cancellationToken);

        }
        catch (IOException)
        {
          return false;
        }

        return true;
      }

      public async global::System.Threading.Tasks.Task GetServer_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp18 = new InternalStructs.GetServer_args();
        await tmp18.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp19 = new InternalStructs.GetServer_result();
        try
        {
          tmp19.Success = await _iAsync.GetServer(tmp18.IdServer, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("GetServer", TMessageType.Reply, seqid), cancellationToken); 
          await tmp19.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp20)
        {
          var tmp21 = $"Error occurred in {GetType().FullName}: {tmp20.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp20, tmp21);
          else
            Console.Error.WriteLine(tmp21);
          var tmp22 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("GetServer", TMessageType.Exception, seqid), cancellationToken);
          await tmp22.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task GetVirtualNodes_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp23 = new InternalStructs.GetVirtualNodes_args();
        await tmp23.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp24 = new InternalStructs.GetVirtualNodes_result();
        try
        {
          tmp24.Success = await _iAsync.GetVirtualNodes(cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("GetVirtualNodes", TMessageType.Reply, seqid), cancellationToken); 
          await tmp24.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp25)
        {
          var tmp26 = $"Error occurred in {GetType().FullName}: {tmp25.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp25, tmp26);
          else
            Console.Error.WriteLine(tmp26);
          var tmp27 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("GetVirtualNodes", TMessageType.Exception, seqid), cancellationToken);
          await tmp27.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

    }

    public class InternalStructs
    {

      public partial class GetServer_args : TBase
      {
        private int _idServer;

        public int IdServer
        {
          get
          {
            return _idServer;
          }
          set
          {
            __isset.idServer = true;
            this._idServer = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool idServer;
        }

        public GetServer_args()
        {
        }

        public GetServer_args DeepCopy()
        {
          var tmp28 = new GetServer_args();
          if(__isset.idServer)
          {
            tmp28.IdServer = this.IdServer;
          }
          tmp28.__isset.idServer = this.__isset.idServer;
          return tmp28;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.I32)
                  {
                    IdServer = await iprot.ReadI32Async(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp29 = new TStruct("GetServer_args");
            await oprot.WriteStructBeginAsync(tmp29, cancellationToken);
            var tmp30 = new TField();
            if(__isset.idServer)
            {
              tmp30.Name = "idServer";
              tmp30.Type = TType.I32;
              tmp30.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
              await oprot.WriteI32Async(IdServer, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is GetServer_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.idServer == other.__isset.idServer) && ((!__isset.idServer) || (global::System.Object.Equals(IdServer, other.IdServer))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if(__isset.idServer)
            {
              hashcode = (hashcode * 397) + IdServer.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp31 = new StringBuilder("GetServer_args(");
          int tmp32 = 0;
          if(__isset.idServer)
          {
            if(0 < tmp32++) { tmp31.Append(", "); }
            tmp31.Append("IdServer: ");
            IdServer.ToString(tmp31);
          }
          tmp31.Append(')');
          return tmp31.ToString();
        }
      }


      public partial class GetServer_result : TBase
      {
        private global::server_service.Server _success;

        public global::server_service.Server Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public GetServer_result()
        {
        }

        public GetServer_result DeepCopy()
        {
          var tmp33 = new GetServer_result();
          if((Success != null) && __isset.@success)
          {
            tmp33.Success = (global::server_service.Server)this.Success.DeepCopy();
          }
          tmp33.__isset.@success = this.__isset.@success;
          return tmp33;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.Struct)
                  {
                    Success = new global::server_service.Server();
                    await Success.ReadAsync(iprot, cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp34 = new TStruct("GetServer_result");
            await oprot.WriteStructBeginAsync(tmp34, cancellationToken);
            var tmp35 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp35.Name = "Success";
                tmp35.Type = TType.Struct;
                tmp35.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp35, cancellationToken);
                await Success.WriteAsync(oprot, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is GetServer_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp36 = new StringBuilder("GetServer_result(");
          int tmp37 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp37++) { tmp36.Append(", "); }
            tmp36.Append("Success: ");
            Success.ToString(tmp36);
          }
          tmp36.Append(')');
          return tmp36.ToString();
        }
      }


      public partial class GetVirtualNodes_args : TBase
      {

        public GetVirtualNodes_args()
        {
        }

        public GetVirtualNodes_args DeepCopy()
        {
          var tmp38 = new GetVirtualNodes_args();
          return tmp38;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp39 = new TStruct("GetVirtualNodes_args");
            await oprot.WriteStructBeginAsync(tmp39, cancellationToken);
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is GetVirtualNodes_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return true;
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp40 = new StringBuilder("GetVirtualNodes_args(");
          tmp40.Append(')');
          return tmp40.ToString();
        }
      }


      public partial class GetVirtualNodes_result : TBase
      {
        private List<global::server_service.VirtualNode> _success;

        public List<global::server_service.VirtualNode> Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public GetVirtualNodes_result()
        {
        }

        public GetVirtualNodes_result DeepCopy()
        {
          var tmp42 = new GetVirtualNodes_result();
          if((Success != null) && __isset.@success)
          {
            tmp42.Success = this.Success.DeepCopy();
          }
          tmp42.__isset.@success = this.__isset.@success;
          return tmp42;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.List)
                  {
                    {
                      var _list43 = await iprot.ReadListBeginAsync(cancellationToken);
                      Success = new List<global::server_service.VirtualNode>(_list43.Count);
                      for(int _i44 = 0; _i44 < _list43.Count; ++_i44)
                      {
                        global::server_service.VirtualNode _elem45;
                        _elem45 = new global::server_service.VirtualNode();
                        await _elem45.ReadAsync(iprot, cancellationToken);
                        Success.Add(_elem45);
                      }
                      await iprot.ReadListEndAsync(cancellationToken);
                    }
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp46 = new TStruct("GetVirtualNodes_result");
            await oprot.WriteStructBeginAsync(tmp46, cancellationToken);
            var tmp47 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp47.Name = "Success";
                tmp47.Type = TType.List;
                tmp47.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
                await oprot.WriteListBeginAsync(new TList(TType.Struct, Success.Count), cancellationToken);
                foreach (global::server_service.VirtualNode _iter48 in Success)
                {
                  await _iter48.WriteAsync(oprot, cancellationToken);
                }
                await oprot.WriteListEndAsync(cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is GetVirtualNodes_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (TCollections.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + TCollections.GetHashCode(Success);
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp49 = new StringBuilder("GetVirtualNodes_result(");
          int tmp50 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp50++) { tmp49.Append(", "); }
            tmp49.Append("Success: ");
            Success.ToString(tmp49);
          }
          tmp49.Append(')');
          return tmp49.ToString();
        }
      }

    }

  }
}
