/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace server_service
{

  public partial class Server : TBase
  {
    private int _idServer;
    private string _address;

    public int IdServer
    {
      get
      {
        return _idServer;
      }
      set
      {
        __isset.idServer = true;
        this._idServer = value;
      }
    }

    public string Address
    {
      get
      {
        return _address;
      }
      set
      {
        __isset.@address = true;
        this._address = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool idServer;
      public bool @address;
    }

    public Server()
    {
    }

    public Server DeepCopy()
    {
      var tmp5 = new Server();
      if(__isset.idServer)
      {
        tmp5.IdServer = this.IdServer;
      }
      tmp5.__isset.idServer = this.__isset.idServer;
      if((Address != null) && __isset.@address)
      {
        tmp5.Address = this.Address;
      }
      tmp5.__isset.@address = this.__isset.@address;
      return tmp5;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                IdServer = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Address = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp6 = new TStruct("Server");
        await oprot.WriteStructBeginAsync(tmp6, cancellationToken);
        var tmp7 = new TField();
        if(__isset.idServer)
        {
          tmp7.Name = "idServer";
          tmp7.Type = TType.I32;
          tmp7.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
          await oprot.WriteI32Async(IdServer, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Address != null) && __isset.@address)
        {
          tmp7.Name = "address";
          tmp7.Type = TType.String;
          tmp7.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
          await oprot.WriteStringAsync(Address, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is Server other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.idServer == other.__isset.idServer) && ((!__isset.idServer) || (global::System.Object.Equals(IdServer, other.IdServer))))
        && ((__isset.@address == other.__isset.@address) && ((!__isset.@address) || (global::System.Object.Equals(Address, other.Address))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.idServer)
        {
          hashcode = (hashcode * 397) + IdServer.GetHashCode();
        }
        if((Address != null) && __isset.@address)
        {
          hashcode = (hashcode * 397) + Address.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp8 = new StringBuilder("Server(");
      int tmp9 = 0;
      if(__isset.idServer)
      {
        if(0 < tmp9++) { tmp8.Append(", "); }
        tmp8.Append("IdServer: ");
        IdServer.ToString(tmp8);
      }
      if((Address != null) && __isset.@address)
      {
        if(0 < tmp9++) { tmp8.Append(", "); }
        tmp8.Append("Address: ");
        Address.ToString(tmp8);
      }
      tmp8.Append(')');
      return tmp8.ToString();
    }
  }

}
