/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace server_service
{

  public partial class VirtualNode : TBase
  {
    private int _idServer;
    private string _hash;

    public int IdServer
    {
      get
      {
        return _idServer;
      }
      set
      {
        __isset.idServer = true;
        this._idServer = value;
      }
    }

    public string Hash
    {
      get
      {
        return _hash;
      }
      set
      {
        __isset.@hash = true;
        this._hash = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool idServer;
      public bool @hash;
    }

    public VirtualNode()
    {
    }

    public VirtualNode DeepCopy()
    {
      var tmp0 = new VirtualNode();
      if(__isset.idServer)
      {
        tmp0.IdServer = this.IdServer;
      }
      tmp0.__isset.idServer = this.__isset.idServer;
      if((Hash != null) && __isset.@hash)
      {
        tmp0.Hash = this.Hash;
      }
      tmp0.__isset.@hash = this.__isset.@hash;
      return tmp0;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                IdServer = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Hash = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp1 = new TStruct("VirtualNode");
        await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
        var tmp2 = new TField();
        if(__isset.idServer)
        {
          tmp2.Name = "idServer";
          tmp2.Type = TType.I32;
          tmp2.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteI32Async(IdServer, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Hash != null) && __isset.@hash)
        {
          tmp2.Name = "hash";
          tmp2.Type = TType.String;
          tmp2.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteStringAsync(Hash, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is VirtualNode other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.idServer == other.__isset.idServer) && ((!__isset.idServer) || (global::System.Object.Equals(IdServer, other.IdServer))))
        && ((__isset.@hash == other.__isset.@hash) && ((!__isset.@hash) || (global::System.Object.Equals(Hash, other.Hash))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.idServer)
        {
          hashcode = (hashcode * 397) + IdServer.GetHashCode();
        }
        if((Hash != null) && __isset.@hash)
        {
          hashcode = (hashcode * 397) + Hash.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp3 = new StringBuilder("VirtualNode(");
      int tmp4 = 0;
      if(__isset.idServer)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("IdServer: ");
        IdServer.ToString(tmp3);
      }
      if((Hash != null) && __isset.@hash)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("Hash: ");
        Hash.ToString(tmp3);
      }
      tmp3.Append(')');
      return tmp3.ToString();
    }
  }

}
